import json
from pathlib import Path
import pandas as pd
import streamlit as st
from src.config import Config
from src.event_bus import read_state

st.set_page_config(page_title="RansomWatch Dashboard", layout="wide")

cfg = Config()
state = read_state(cfg.STATE_JSON)

st.title("🛡️ RansomWatch — Ransomware Behavior Detection (Defensive)")
st.caption("Monitors a folder for ransomware-like behavior patterns (mass changes, extension spikes, entropy spikes).")

col1, col2, col3 = st.columns(3)
with col1:
    st.metric("Watch Folder", cfg.WATCH_PATH)
with col2:
    st.metric("Window (seconds)", cfg.WINDOW_SECONDS)
with col3:
    st.metric("Mass Threshold", cfg.MASS_CHANGE_THRESHOLD)

alerts = state.get("alerts", [])
events = state.get("events", [])

st.subheader("🚨 Alerts")
if alerts:
    df_a = pd.DataFrame(alerts)
    st.dataframe(df_a.sort_values("ts", ascending=False), use_container_width=True, height=260)
else:
    st.info("No alerts yet. Run monitor.py and generate activity in the watch folder.")

st.subheader("📌 Recent Events")
if events:
    df_e = pd.DataFrame(events)
    st.dataframe(df_e.sort_values("ts", ascending=False), use_container_width=True, height=320)
else:
    st.write("No events yet.")

st.subheader("🧪 Safe Testing")
st.markdown(
    """Run a **benign** activity generator (no malware, no encryption) to trigger the rules:
```bash
python monitor.py --safe-test
```
"""
)

st.subheader("📂 Logs")
st.markdown(
    """- `logs/events.csv` — event stream (create/modify/delete/move)  
- `logs/alerts.csv` — alerts generated by rules  
- `logs/state.json` — state file used by the dashboard  
"""
)
